[workspace]
resolver = "2"

members = [
    "mouse_tracker",
    "settings",
    "errors",
    "embctl",
    "config",
    "embgui",
    "service-manager-util",
    "window-spawn-util",
    "installer"
]
