import { Switch, GridBox, ListView, ScrollView, HorizontalBox, VerticalBox, Palette } from "std-widgets.slint";

export component Page inherits VerticalBox {
    in property<string> title: "title";
    in property<string> description: "description";
    in property<bool> show-enable-switch: true;

    HorizontalLayout {
        Text {
            font-size: 20px;
            text <=> root.title;
        }

        // Spacer
        Rectangle {}
    }

    @children
}