import { HorizontalBox, VerticalBox } from "std-widgets.slint";

export component SuccessWindow inherits Window {
    title: "Emergency Backup";
    in property<string> message;
    in property <image> success_icon;


    HorizontalLayout {
        HorizontalBox {
            Image {
                padding: 20px;
                source: success_icon;
                width: 50px;
                height: 50px;
            }
            
            VerticalBox {
                Text {
                    text: message;
                }
            }
        }
    }
}
